steps:
  # Build version image
  - name: gcr.io/cloud_builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/version:$COMMIT_SHA
      - .

  # Push version image to Google Cloud Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/version:$COMMIT_SHA
 
# deploy the Kubernetes by useing yaml files
  - name: gcr.io/cloud-builders/gke-deploy
    args:
    - run
    - --filename=./kubernetes-resource-file.yaml
    - '--image'
    - 'gcr.io/$PROJECT_ID/version:$COMMIT_SHA'

substitutions:
    _CUSTOM_REGION: us-central1-a
    _CUSTOM_CLUSTER: gke-cluster-poc
