steps:
  # Build version image
  - name: gcr.io/cloud_builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/version:$gcppoc
      - .

  # Push version image to Google Cloud Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/version:$gcppoc

  # Configure a kubectl workspace for this project
  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  # Deploy with Helm
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - -i
      - version
      - ./kubernetes-resource-file.yaml
      - --set
      - image.repository=gcr.io/$PROJECT_ID/version,image.tag=$gcppoc
      - -f
      - ./kubernetes-resource-file/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=false
      - TILLER_NAMESPACE=kube-system
timeout: 1200s
substitutions:
  _CUSTOM_REGION: us-central1-a
  _CUSTOM_CLUSTER: gke-cluster-poc
