steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/version:latest', '-t', 'gcr.io/$PROJECT_ID/version:$versioncontainer', '-t', 'gcr.io/$PROJECT_ID/version:$BUILD_ID', '.']
  
   
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/version:$versioncontainer']
  
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=./kubernetes-resource-file.yaml
    - '--image'
    - 'gcr.io/$PROJECT_ID/version:$versioncontainer'
    - '--location'
    - 'us-central1-a'
    - '--cluster'
    - 'gke-cluster-poc'  
  
