steps:
#First Clone from Google Cloud Source Repository  
# - name: 'gcr.io/cloud-builders/git'
 # args: ['clone','https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']
  
#Build the image   
  - name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ["build", "-t", "$_IMAGE_NAME:$_IMAGE_VERSION", ".", "-f", "$_DOCKERFILE_PATH"]
  
  #push the image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ["push", "$_IMAGE_NAME:$_IMAGE_VERSION"]
  
  
  #deply the application
  - name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Prepare deploy'
  args:
  - 'prepare'
 # - '--filename=$_K8S_YAML_PATH'
  - '--image=$_IMAGE_NAME:$_IMAGE_VERSION'
  - '--app=$_K8S_APP_NAME'
  - '--version=$_IMAGE_VERSION'
  - '--namespace=$_K8S_NAMESPACE'
  - '--output=output'
  - '--annotation=gcb-build-id=$BUILD_ID'
  
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Apply deploy'
  args:
  - 'apply'
 # - '--filename=$_OUTPUT_BUCKET_PATH/expanded/*'
  - '--namespace=$_K8S_NAMESPACE'
  - '--cluster=$_GKE_CLUSTER'
  - '--location=$_GKE_LOCATION'
images:
- '$_IMAGE_NAME:$_IMAGE_VERSION'

tags: [$_K8S_APP_NAME']


  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: cloud-build-poc-gke
    _ZONE: us-central1-a
    _GKE_CLUSTER: gke-cluster-poc
    
    
    images:
- '$_IMAGE_NAME:$_IMAGE_VERSION'

tags: [$_K8S_APP_NAME']
    
    
options:
    substitution_option: 'ALLOW_LOOSE'
