---
apiVersion: v1
kind: Pod
metadata:
  name: version-pod
  labels:
    app: frontend
spec:
  containers:
    - image: gcr.io/cloud-build-poc-gke/hello-world-service:v1.0
      name: version
      ports:
        - containerPort: 80
          name: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-deploy
  labels:
    app: frontend
    color: green
spec:
  replicas: 1
  template:
    metadata:
      name: green-deploy
      labels:
        app: frontend
        color: green
    spec:
      containers:
        - image: gcr.io/cloud-build-poc-gke/hello-world-service:v1.0
          name: version-deploy
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: frontend
      color: green

---
apiVersion: v1
kind: Service
metadata:
  name: version-service
spec:
  selector:
    app: frontend
  ports:
    - targetPort: 8080
      port: 80
  type: LoadBalancer
